### ISSUE TITLE
Will this accept contributions?

### ISSUE THREAD

**Issue by Kyjor** [YongHee-Kim/GameDataManager.jl#7]
Hello, I just happened upon this tool, and it looks like it could be very useful in the **near-ish** future for the work on my game engine. It seems like it's been awhile since this has had activity. But eventually, I'd probably like to use this and bring it up to date for games I create with my engine. Will this project be accepting new contributions? Thank you.

**Comment by YongHee-Kim** [comment]
Hello, Yes absolutely. I had not touched this because I've moved on from the game project using this. 
This had been used in the small dev team for 2+ years and it was stable after the initial setup.  

But I do still love to work on this if you can post a feature request here. and feel free to ask any questions
Also https://github.com/Kyjor/JulGame.jl looks amazing👍 I believe Julia would be great for a game development and would love to see it happening

**Comment by Kyjor** [comment]
Sounds amazing, thank you! It will probably be a couple of months until I will dig into this, but I plan on using it for a game I will be starting soon. Once I start using it, I will let you know and begin asking questions. 

Thanks about JulGame. I'm hoping to have a first user-friendly release in the coming months. Hopefully it will get people excited about Julia game development!
